package com.kamilabiyev.todoapp.dto;


import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import javax.validation.constraints.NotBlank;

import lombok.Data;

@Data
@ApiModel(value = "Todo",
        description = "A list of tasks you need to complete or things that you want to do")
public class ToDoDTO {
    @ApiModelProperty("Id of todo, that auto generated by the db.")
    private Integer id;

    @ApiModelProperty(value = "Title of the todo.",
            example = "Home work",
            required = true)
    @NotBlank(message = "Title is required field.")
    private String title;
    @ApiModelProperty(value = "Content of the todo.",
            example = "Learn reflection",
            required = true)
    @NotBlank(message = "Content is required field.")
    private String content;

    @ApiModelProperty(value = "Specify that todo is completed or not.",
            example = "true",
            required = false)
    private Boolean isCompleted;
}
